# 10 req/s per IP; zone size 10M
limit_req_zone $binary_remote_addr zone=ghvshort_req:10m rate=10r/s;

# limit concurrent connections per ip
limit_conn_zone $binary_remote_addr zone=ghvshort_conn:10m;

server_tokens off;
